In [149]:
from bookinz.storage import BronzeLayer

In [ ]:
bl = BronzeLayer("data")

# Cheapest available hotels in Amsterdam
df = bl.query("""
    with query as (
        select
            facility_id,
            name,
            currency,
            search_area,
            neighbourhood,
            accommodation_type,
            tags,
            distance_from_center_km,
            date_diff('day', cast(checkin_date as date), cast(checkout_date as date)) as num_nights,
            total_price,
            round(total_price / nullif(date_diff('day', cast(checkin_date as date), cast(checkout_date as date)), 0), 2) as price_per_night,
            round((total_price) / num_adults, 2) as price_per_person,
            round((total_price) / nullif(date_diff('day', cast(checkin_date as date), cast(checkout_date as date)) * num_adults, 0), 2) as price_per_night_per_person,
            url
        from bronze
              
    )
    
    select
        *
    from query
    where
        1 = 1 
        and price_per_night_per_person <= 80
        --and (
        --      (distance_from_center_km <= 3 and search_area = 'Budapest__Hungary')
        --      or
        --      (distance_from_center_km <= 1.5 and search_area = 'Ponta_Delgada__Portugal')
        --    )

""")
df

,facility_id,name,currency,search_area,distance_from_center_km,num_nights,total_price,price_per_night,price_per_person,price_per_night_per_person,url
0,ibis-budapest-stadium,ibis Budapest Stadium,€,Budapest__Hungary,4.0,3,472.0,157.33,157.33,52.44,https://www.booking.com/hotel/hu/ibis-budapest...
1,tribe-budapest-airport,TRIBE Budapest Airport,€,Budapest__Hungary,17.2,3,576.0,192.00,192.00,64.00,https://www.booking.com/hotel/hu/tribe-budapes...
2,aquincum-hotel,Verdi Budapest Aquincum,€,Budapest__Hungary,4.5,3,553.0,184.33,184.33,61.44,https://www.booking.com/hotel/hu/aquincum-hote...
3,maria-apartment,MARIA Apartment,€,Budapest__Hungary,1.2,3,216.0,72.00,72.00,24.00,https://www.booking.com/hotel/hu/maria-apartme...
4,astoria,Danubius Hotel Astoria City Center,€,Budapest__Hungary,NaN,3,471.0,157.00,157.00,52.33,https://www.booking.com/hotel/hu/astoria.en-gb...
...,...,...,...,...,...,...,...,...,...,...,...
158,casa-serafina-in-prati-district,Casa Serafina in Prati district,€,Rome__Italy,3.2,14,2884.0,206.00,576.80,41.20,https://www.booking.com/hotel/it/casa-serafina...
159,la-lanterna-di-san-pietro-b-amp-b,La Lanterna Di San Pietro,€,Rome__Italy,3.4,14,4707.0,336.21,941.40,67.24,https://www.booking.com/hotel/it/la-lanterna-d...
160,da-adriana-al-vaticano-roma,Da Adriana al vaticano,€,Rome__Italy,2.8,14,2926.0,209.00,585.20,41.80,https://www.booking.com/hotel/it/da-adriana-al...
161,elisas-trevi-fountain-buddyrent-roma,Elisa's Trevi Fountain BuddyRent,€,Rome__Italy,0.8,14,4973.0,355.21,994.60,71.04,https://www.booking.com/hotel/it/elisas-trevi-...
162,le-suites-del-duca-c-roma-prati,Le Suites del Duca C - Roma Prati,€,Rome__Italy,1.4,14,4237.0,302.64,847.40,60.53,https://www.booking.com/hotel/it/le-suites-del...

In [152]:
df

                                                  url
0   https://www.booking.com/hotel/hu/aquaworld-res...
1   https://www.booking.com/hotel/hu/ibis-budapest...
2   https://www.booking.com/hotel/hu/tribe-budapes...
3   https://www.booking.com/hotel/hu/aquincum-hote...
4   https://www.booking.com/hotel/hu/maria-apartme...
..                                                ...
57  https://www.booking.com/hotel/pt/the-rock-gues...
58  https://www.booking.com/hotel/pt/solar-dos-can...
59  https://www.booking.com/hotel/pt/acores-atlant...
60  https://www.booking.com/hotel/pt/guestready-ga...
61  https://www.booking.com/hotel/pt/sao-miguel-pa...

[62 rows x 1 columns]